config/routes.rb
Rails.application.routes.draw do

  resources :watchings

  get 'users/new'
  get "logout", to: "sessions#logout", as: :logout
  root 'projects#index'

  resource :sessions 
  resource :users
  resources :updates

  resources :projects do
    resources :updates
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :watchings
	has_many :users, through: :watchings
	has_many :updates
		validates :who, presence: true
		validates :name, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @projects = Project.all
    @update = Update.new
    @watching= Watching.new
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    if @project.author == current_user.username
    else
      redirect_to root_path, notice: 'You do not have access to that page'
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project has been updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    updates = Update.where(project_id: @project.id)
    updates.each do |update|
      update.destroy
    end
    watchings = Watching.where(project_id: @project.id)
    watchings.each do |watching|
      watching.destroy
    end
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :who, :how, :editor, :latest_updated, :author)
    end
    def name
      @project.name
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="well">
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><span class="label label-danger"><%= pluralize(@project.errors.count, "error") %> during project creation</span></h2>
  <div class="error-reasons">
      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
      </ul>
    </div>
  <% end %>

<div class="well">
  <div class="field">
    <%= f.text_field :name, class:'form-control', id:'short-form', placeholder:'Project name' %>
  </div>
  <br>
  <div class="field">
    <%= f.text_area :description, class:'form-control', placeholder:'Brief description...' %>
  </div>
  <br>
  <div class="field">
    <%= f.text_area :who, class:'form-control', placeholder:'Who\'s involved...' %>
  </div>    
  <br>
  <div class="field">
    <%= f.text_area :how, class:'form-control', placeholder:'How others can become involved...' %>
  </div>
  <br>
  <% if @project.latest_updated.nil? %>
  <%= f.hidden_field :author, value: current_user.username %>
    <% @project.latest_updated = Time.now %>  
    <% @project.save %>
  <% else %>
    <%= f.hidden_field :editor, value: current_user.username %>
    <% update = Update.new %>
    <% update.project_id = @project.id %>
    <% update.project_edit = true %>
    <% update.who = current_user.username %>
    <% update.description = "Project eddited" %>
    <% update.save %>
  <% end %>
    
    <%= f.submit 'Submit', class:'btn btn-primary btn-sm btn-submit'%>

<% end %>

app/views/projects/edit.html.erb
<a class="list-group-item active">
<h1>Editing project</h1>
</a>
<%= render 'form' %>
<%= link_to 'Back', @project, class:'btn btn-primary btn-sm btn-cancel' %>

app/views/projects/index.html.erb
<div class="container">

  <div class="row">

    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8" >

        <span class="list-group-item active update-title">
          Project  
          <span class="float-right">
            Updated
          </span>
        </span>
      <ul class="list-group">
      <div class='word-break'>
      <% @projects.order('latest_updated DESC').each do |project| %>

       <a href="/projects/<%= project.id %>" class="list-group-item">
          <div class="reduce">
          <strong><%= project.name %></strong>

        <span class="label label-default" id="time-ago">
            <% updated = project.updates.order('created_at DESC').first %>
            <% if project.updates.empty? %>
            No updates
            <% else %>
            <%= time_ago_in_words(updated.created_at) %>    
               by 
          <%= updated.who %>
          
            <% end %>
      </div>
        </span>
       </a>
          <% end %> 
      </ul>
        <div class="btn-group">
        <% if current_user %>
        <%= link_to 'Create Project', new_project_path, class:'btn btn-primary btn-sm' %>
        <% else %>
        <%= link_to 'Create Project', new_sessions_path, class:'btn btn-primary btn-sm' %>
       <!--  <%= link_to 'Log in to create a project!', new_sessions_path %> -->
        <% end %>
      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" >
      <!-- Mission area -->
      <div class="well">
      <strong>Welcome to the Project Tracker MVP!</strong>
      <br>
        Our goal is to create a way for LAB Miami members to see what's going on in the LAB. You can create a listing for a LAB project you are currently working on, or read about other projects going on! Users can now watch a project to view a filtered updates feed.
      <br>
      <br>
        - In Project Tracker, a project is anything that takes work.
      </div>

      <div class="well" >
        <p>
        For any questions you can reach me at:
        <br>
        <em>Ortiz_Frank@hotmail.com</em>
        </p>
        <strong>Known issues:</strong>
        <br>
        Usernames are case sensitive
        <br>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<a class="list-group-item active">
<h1><span class="info">Create a Project</span></h1>
</a>
<%= render 'form' %>
	<%= link_to 'Cancel Creation', projects_path, class:'btn btn-primary btn-sm btn-cancel' %>
		</div>
 	</div>
</div>

app/views/projects/show.html.erb
<div class="container">

  <div class="row">

    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8" >
   
        <div class="panel-heading">
          <br>
        <h3 class="project-title"><%= @project.name %></h3>
        </div>
        <div class="panel panel-defult">  
        <div class="panel-title"><span class="author">Posted by: <%= @project.author %></span></div>
        <div class="panel-body">
          <%= simple_format h(@project.description).gsub(/\n/, '<br/>') %>
        </div>
      </div>
      <div class="panel panel-defult"> 
        <div class="panel-heading">
          <h3 class="panel-title">Who's involved:</h3>
          </div>
          <div class="panel panel-defult">
        <div class="panel-body">
          <%= simple_format h(@project.who).gsub(/\n/, '<br/>') %>
        </div>
      </div>
        <div class="panel-heading">
          <h3 class="panel-title">How others can become involved:</h3>
        </div>
        <div class="panel-body"><%= simple_format h(@project.how).gsub(/\n/, '<br/>') %></div> 

 </div>

      <%= @project.watchings.count %> Curently watching this project
      <% if current_user %>
        <% project_watching = @project.watchings.find_by user_id: current_user.id %>
        <p>
      <% if project_watching.nil? %>
         <%= form_for(@watching) do |f| %>
        <%= f.hidden_field :project_id, value: @project.id %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.submit 'Watch', class:'btn btn-primary btn-sm' %>
        <% end %>
      <% else %>
        <%= link_to 'Unwatch', project_watching, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
        </p>
      <% else %>
      <% end %>


      <% if @project.editor %>
        <span id="edited"><em><p>Last edited by <%= @project.editor %> <%= time_ago_in_words(@project.updated_at) %></p></em></span>
      <% else %>
      <% end %>
      <% if current_user %>
        <% if @project.author == current_user.username %>
          <%= link_to 'Edit Project', edit_project_path(@project), class:'btn btn-warning btn-sm' %>
          <%= link_to 'Remove Project', @project, method: :delete, data: { confirm: 'Are you sure you want to delete this Project?' }, class:'btn btn-danger btn-sm'  %>
        <% elsif @project.editor == current_user.username %>
          <%= link_to 'Edit Project', edit_project_path(@project), class:'btn btn-warning btn-sm' %>
        <% else %>
        <% end %>
      <% else %>
      <% end %>

    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
      <p class="center lead"><strong>Updates</strong></p>
      <div class="well flow">
        <% if session[:user_id] %>
        <%= render 'updates/form' %>
        <% else %>
        <p>
          <p><em>You must be logged in to post an update.</em></p>
        </p>
        <% end %>


        <% @project.updates.order('created_at DESC').each do |update| %>

        <% if update.project_edit %>
            <em><p id="edited">Project edited by <%= update.who %> <%= time_ago_in_words(update.created_at) %></p></em>
        <% else %>

          <div class="list-group">
            <span class="list-group-item active">
              <%= time_ago_in_words(update.created_at)%>
              by
              <em><%= update.who %></em>  
            </span>    
            <div class="well">
              <div center="center" id="individual-update">
                <%= simple_format h(update.description).gsub(/\n/, '<br/>') %>
              </div>
              <% if update.updated_at == update.created_at %>
              <% else %>
              <span class="well-corner" id="edited">Edited <%= time_ago_in_words(update.updated_at)%><span>
              <% end %>
            </div>
            <% if current_user %>
              <% if update.who == current_user.username %>
                <%= link_to 'Edit', edit_update_path(update), class:'btn btn-warning btn-xs' %>
                <%= link_to 'Remove', update, method: :delete, data: { confirm: 'Are you sure you want to delete this update?' }, class:'btn btn-danger btn-xs' %>
              <% else %>
              <% end %>
            <% else %>
            <% end %>
          </div>
          <% end %>

        <% end %>


      </div>
    </div>
  </div>

</div>