config/routes.rb
Rails.application.routes.draw do

  resources :watchings

  get 'users/new'
  get "logout", to: "sessions#logout", as: :logout
  root 'projects#index'

  resource :sessions 
  resource :users
  resources :updates

  resources :projects do
    resources :updates
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>Project Tracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <a class="navbar-brand" href="/projects">Project Tracker</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">

      	<% if current_page?(updates_path)%>
        <li><a href="projects">Projects</a></li>
        <li class="active"><a href="updates">Updates</a></li>
        <% if session[:user_id] %>
        <li><a href="/watchings">Watch List</a></li>
        <% else %>
        <% end %>
        <% elsif current_page?(projects_path) %>
        <li class="active"><a href="projects">Projects</a></li>
        <li><a href="updates">Updates</a></li>
        <% if session[:user_id] %>
        <li><a href="/watchings">Watch List</a></li>
        <% else %>
        <% end %>
        <% elsif current_page?(watchings_path) %>
        <li><a href="projects">Projects</a></li>
        <li><a href="updates">Updates</a></li>
        <% if session[:user_id] %>
        <li class="active"><a href="/watchings">Watch List</a></li>
        <% else %>
        <% end %>
        <% else %>
        <li><a href="/projects">Projects</a></li>
        <li><a href="/updates">Updates</a></li>
        <% if session[:user_id] %>
        <li><a href="/watchings">Watch List</a></li>
        <% else %>
        <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">

        <% if session[:user_id] %>
            <div id="logout">
              <%= link_to 'Log out', logout_path, class:'btn btn-primary btn-xs btn', id:'logout' %>
            </div>
        <% else %>
            <div id="login">
                <li><%= link_to 'Log in', new_sessions_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  <%= link_to 'Sign up', new_users_path %></li>
            </div>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

<div class="container">
  <div id="notice-box">
    <span id="notice" ><%= notice %></span>
  </div>
<%= yield %>
</div>

</body>
</html>